name: qr_generate
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #stateManagment
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.9

  #share
  screenshot: ^1.2.3
  share_plus: ^4.0.10

  #qr
  qr_flutter: ^4.0.0

  #ui
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  #router
  auto_route_generator: ^4.0.0
  
  #stateManagment
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7


flutter:
  assets:
    - assets/icons/


  uses-material-design: true
